//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya5
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заключение договора.
    /// </summary>
    // *** Start programmer edit section *** (ЗаключениеДоговора CustomAttributes)

    // *** End programmer edit section *** (ЗаключениеДоговора CustomAttributes)
    [AutoAltered()]
    [Caption("Заключение договора")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаключениеДоговораE", new string[] {
            "Дата as \'Дата\'",
            "Номер as \'Номер\'",
            "Тип as \'Тип\'",
            "Стоимость as \'Стоимость\'"})]
    public class ЗаключениеДоговора : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private int fНомер;
        
        private IIS.Kursovaya5.ТипДоговора fТип;
        
        private int fСтоимость;
        
        private IIS.Kursovaya5.ОказаниеКонсультаций fОказаниеКонсультаций;
        
        private IIS.Kursovaya5.ДиректорОтделаПоРаботеСКлиентами fДиректорОтделаПоРаботеСКлиентами;
        
        private IIS.Kursovaya5.Клиент fКлиент;
        
        // *** Start programmer edit section *** (ЗаключениеДоговора CustomMembers)

        // *** End programmer edit section *** (ЗаключениеДоговора CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ЗаключениеДоговора.Дата CustomAttributes)

        // *** End programmer edit section *** (ЗаключениеДоговора.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ЗаключениеДоговора.Дата Get start)

                // *** End programmer edit section *** (ЗаключениеДоговора.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ЗаключениеДоговора.Дата Get end)

                // *** End programmer edit section *** (ЗаключениеДоговора.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаключениеДоговора.Дата Set start)

                // *** End programmer edit section *** (ЗаключениеДоговора.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ЗаключениеДоговора.Дата Set end)

                // *** End programmer edit section *** (ЗаключениеДоговора.Дата Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ЗаключениеДоговора.Номер CustomAttributes)

        // *** End programmer edit section *** (ЗаключениеДоговора.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ЗаключениеДоговора.Номер Get start)

                // *** End programmer edit section *** (ЗаключениеДоговора.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ЗаключениеДоговора.Номер Get end)

                // *** End programmer edit section *** (ЗаключениеДоговора.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаключениеДоговора.Номер Set start)

                // *** End programmer edit section *** (ЗаключениеДоговора.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ЗаключениеДоговора.Номер Set end)

                // *** End programmer edit section *** (ЗаключениеДоговора.Номер Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (ЗаключениеДоговора.Стоимость CustomAttributes)

        // *** End programmer edit section *** (ЗаключениеДоговора.Стоимость CustomAttributes)
        public virtual int Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (ЗаключениеДоговора.Стоимость Get start)

                // *** End programmer edit section *** (ЗаключениеДоговора.Стоимость Get start)
                int result = this.fСтоимость;
                // *** Start programmer edit section *** (ЗаключениеДоговора.Стоимость Get end)

                // *** End programmer edit section *** (ЗаключениеДоговора.Стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаключениеДоговора.Стоимость Set start)

                // *** End programmer edit section *** (ЗаключениеДоговора.Стоимость Set start)
                this.fСтоимость = value;
                // *** Start programmer edit section *** (ЗаключениеДоговора.Стоимость Set end)

                // *** End programmer edit section *** (ЗаключениеДоговора.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// Тип.
        /// </summary>
        // *** Start programmer edit section *** (ЗаключениеДоговора.Тип CustomAttributes)

        // *** End programmer edit section *** (ЗаключениеДоговора.Тип CustomAttributes)
        public virtual IIS.Kursovaya5.ТипДоговора Тип
        {
            get
            {
                // *** Start programmer edit section *** (ЗаключениеДоговора.Тип Get start)

                // *** End programmer edit section *** (ЗаключениеДоговора.Тип Get start)
                IIS.Kursovaya5.ТипДоговора result = this.fТип;
                // *** Start programmer edit section *** (ЗаключениеДоговора.Тип Get end)

                // *** End programmer edit section *** (ЗаключениеДоговора.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаключениеДоговора.Тип Set start)

                // *** End programmer edit section *** (ЗаключениеДоговора.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (ЗаключениеДоговора.Тип Set end)

                // *** End programmer edit section *** (ЗаключениеДоговора.Тип Set end)
            }
        }
        
        /// <summary>
        /// Заключение договора.
        /// </summary>
        // *** Start programmer edit section *** (ЗаключениеДоговора.ДиректорОтделаПоРаботеСКлиентами CustomAttributes)

        // *** End programmer edit section *** (ЗаключениеДоговора.ДиректорОтделаПоРаботеСКлиентами CustomAttributes)
        [PropertyStorage(new string[] {
                "ДиректорОтделаПоРаботеСКлиентами"})]
        [NotNull()]
        public virtual IIS.Kursovaya5.ДиректорОтделаПоРаботеСКлиентами ДиректорОтделаПоРаботеСКлиентами
        {
            get
            {
                // *** Start programmer edit section *** (ЗаключениеДоговора.ДиректорОтделаПоРаботеСКлиентами Get start)

                // *** End programmer edit section *** (ЗаключениеДоговора.ДиректорОтделаПоРаботеСКлиентами Get start)
                IIS.Kursovaya5.ДиректорОтделаПоРаботеСКлиентами result = this.fДиректорОтделаПоРаботеСКлиентами;
                // *** Start programmer edit section *** (ЗаключениеДоговора.ДиректорОтделаПоРаботеСКлиентами Get end)

                // *** End programmer edit section *** (ЗаключениеДоговора.ДиректорОтделаПоРаботеСКлиентами Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаключениеДоговора.ДиректорОтделаПоРаботеСКлиентами Set start)

                // *** End programmer edit section *** (ЗаключениеДоговора.ДиректорОтделаПоРаботеСКлиентами Set start)
                this.fДиректорОтделаПоРаботеСКлиентами = value;
                // *** Start programmer edit section *** (ЗаключениеДоговора.ДиректорОтделаПоРаботеСКлиентами Set end)

                // *** End programmer edit section *** (ЗаключениеДоговора.ДиректорОтделаПоРаботеСКлиентами Set end)
            }
        }
        
        /// <summary>
        /// Заключение договора.
        /// </summary>
        // *** Start programmer edit section *** (ЗаключениеДоговора.ОказаниеКонсультаций CustomAttributes)

        // *** End programmer edit section *** (ЗаключениеДоговора.ОказаниеКонсультаций CustomAttributes)
        [PropertyStorage(new string[] {
                "ОказаниеКонсультаций"})]
        [NotNull()]
        public virtual IIS.Kursovaya5.ОказаниеКонсультаций ОказаниеКонсультаций
        {
            get
            {
                // *** Start programmer edit section *** (ЗаключениеДоговора.ОказаниеКонсультаций Get start)

                // *** End programmer edit section *** (ЗаключениеДоговора.ОказаниеКонсультаций Get start)
                IIS.Kursovaya5.ОказаниеКонсультаций result = this.fОказаниеКонсультаций;
                // *** Start programmer edit section *** (ЗаключениеДоговора.ОказаниеКонсультаций Get end)

                // *** End programmer edit section *** (ЗаключениеДоговора.ОказаниеКонсультаций Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаключениеДоговора.ОказаниеКонсультаций Set start)

                // *** End programmer edit section *** (ЗаключениеДоговора.ОказаниеКонсультаций Set start)
                this.fОказаниеКонсультаций = value;
                // *** Start programmer edit section *** (ЗаключениеДоговора.ОказаниеКонсультаций Set end)

                // *** End programmer edit section *** (ЗаключениеДоговора.ОказаниеКонсультаций Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Kursovaya5.Клиент.
        /// </summary>
        // *** Start programmer edit section *** (ЗаключениеДоговора.Клиент CustomAttributes)

        // *** End programmer edit section *** (ЗаключениеДоговора.Клиент CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Клиент"})]
        public virtual IIS.Kursovaya5.Клиент Клиент
        {
            get
            {
                // *** Start programmer edit section *** (ЗаключениеДоговора.Клиент Get start)

                // *** End programmer edit section *** (ЗаключениеДоговора.Клиент Get start)
                IIS.Kursovaya5.Клиент result = this.fКлиент;
                // *** Start programmer edit section *** (ЗаключениеДоговора.Клиент Get end)

                // *** End programmer edit section *** (ЗаключениеДоговора.Клиент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаключениеДоговора.Клиент Set start)

                // *** End programmer edit section *** (ЗаключениеДоговора.Клиент Set start)
                this.fКлиент = value;
                // *** Start programmer edit section *** (ЗаключениеДоговора.Клиент Set end)

                // *** End programmer edit section *** (ЗаключениеДоговора.Клиент Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаключениеДоговораE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаключениеДоговораE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаключениеДоговораE", typeof(IIS.Kursovaya5.ЗаключениеДоговора));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ЗаключениеДоговора.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfЗаключениеДоговора CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfЗаключениеДоговора CustomAttributes)
    public class DetailArrayOfЗаключениеДоговора : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Kursovaya5.DetailArrayOfЗаключениеДоговора members)

        // *** End programmer edit section *** (IIS.Kursovaya5.DetailArrayOfЗаключениеДоговора members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ЗаключениеДоговора by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ЗаключениеДоговора.
        /// </summary>
        public DetailArrayOfЗаключениеДоговора(IIS.Kursovaya5.Клиент fКлиент) : 
                base(typeof(ЗаключениеДоговора), ((ICSSoft.STORMNET.DataObject)(fКлиент)))
        {
        }
        
        public IIS.Kursovaya5.ЗаключениеДоговора this[int index]
        {
            get
            {
                return ((IIS.Kursovaya5.ЗаключениеДоговора)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Kursovaya5.ЗаключениеДоговора dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
