//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya5
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Клиент.
    /// </summary>
    // *** Start programmer edit section *** (Клиент CustomAttributes)

    // *** End programmer edit section *** (Клиент CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлиентE", new string[] {
            "id as \'Id\'",
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "НомерТелефона as \'Номер телефона\'",
            "НаимОрганицации as \'Наим органицации\'"})]
    [AssociatedDetailViewAttribute("КлиентE", "РасторжениеДоговора", "РасторжениеДоговораE", true, "", "Расторжение договора", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("КлиентE", "ЗаключениеДоговора", "ЗаключениеДоговораE", true, "", "Заключение договора", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("КлиентE", "ОказаниеКонсультаций", "ОказаниеКонсультацийE", true, "", "Оказание консультаций", true, new string[] {
            ""})]
    [View("КлиентL", new string[] {
            "id as \'Id\'",
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "НомерТелефона as \'Номер телефона\'",
            "НаимОрганицации as \'Наим органицации\'"})]
    public class Клиент : ICSSoft.STORMNET.DataObject
    {
        
        private int fid;
        
        private string fФамилия;
        
        private string fИмя;
        
        private string fОтчество;
        
        private string fНомерТелефона;
        
        private string fНаимОрганицации;
        
        private IIS.Kursovaya5.DetailArrayOfЗаключениеДоговора fЗаключениеДоговора;
        
        private IIS.Kursovaya5.DetailArrayOfОказаниеКонсультаций fОказаниеКонсультаций;
        
        private IIS.Kursovaya5.DetailArrayOfРасторжениеДоговора fРасторжениеДоговора;
        
        // *** Start programmer edit section *** (Клиент CustomMembers)

        // *** End programmer edit section *** (Клиент CustomMembers)

        
        /// <summary>
        /// id.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.id CustomAttributes)

        // *** End programmer edit section *** (Клиент.id CustomAttributes)
        public virtual int id
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.id Get start)

                // *** End programmer edit section *** (Клиент.id Get start)
                int result = this.fid;
                // *** Start programmer edit section *** (Клиент.id Get end)

                // *** End programmer edit section *** (Клиент.id Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.id Set start)

                // *** End programmer edit section *** (Клиент.id Set start)
                this.fid = value;
                // *** Start programmer edit section *** (Клиент.id Set end)

                // *** End programmer edit section *** (Клиент.id Set end)
            }
        }
        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Имя CustomAttributes)

        // *** End programmer edit section *** (Клиент.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Имя Get start)

                // *** End programmer edit section *** (Клиент.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Клиент.Имя Get end)

                // *** End programmer edit section *** (Клиент.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Имя Set start)

                // *** End programmer edit section *** (Клиент.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Клиент.Имя Set end)

                // *** End programmer edit section *** (Клиент.Имя Set end)
            }
        }
        
        /// <summary>
        /// НаимОрганицации.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.НаимОрганицации CustomAttributes)

        // *** End programmer edit section *** (Клиент.НаимОрганицации CustomAttributes)
        [StrLen(255)]
        public virtual string НаимОрганицации
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.НаимОрганицации Get start)

                // *** End programmer edit section *** (Клиент.НаимОрганицации Get start)
                string result = this.fНаимОрганицации;
                // *** Start programmer edit section *** (Клиент.НаимОрганицации Get end)

                // *** End programmer edit section *** (Клиент.НаимОрганицации Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.НаимОрганицации Set start)

                // *** End programmer edit section *** (Клиент.НаимОрганицации Set start)
                this.fНаимОрганицации = value;
                // *** Start programmer edit section *** (Клиент.НаимОрганицации Set end)

                // *** End programmer edit section *** (Клиент.НаимОрганицации Set end)
            }
        }
        
        /// <summary>
        /// НомерТелефона.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.НомерТелефона CustomAttributes)

        // *** End programmer edit section *** (Клиент.НомерТелефона CustomAttributes)
        [StrLen(255)]
        public virtual string НомерТелефона
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.НомерТелефона Get start)

                // *** End programmer edit section *** (Клиент.НомерТелефона Get start)
                string result = this.fНомерТелефона;
                // *** Start programmer edit section *** (Клиент.НомерТелефона Get end)

                // *** End programmer edit section *** (Клиент.НомерТелефона Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.НомерТелефона Set start)

                // *** End programmer edit section *** (Клиент.НомерТелефона Set start)
                this.fНомерТелефона = value;
                // *** Start programmer edit section *** (Клиент.НомерТелефона Set end)

                // *** End programmer edit section *** (Клиент.НомерТелефона Set end)
            }
        }
        
        /// <summary>
        /// Отчество.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Отчество CustomAttributes)

        // *** End programmer edit section *** (Клиент.Отчество CustomAttributes)
        [StrLen(255)]
        public virtual string Отчество
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Отчество Get start)

                // *** End programmer edit section *** (Клиент.Отчество Get start)
                string result = this.fОтчество;
                // *** Start programmer edit section *** (Клиент.Отчество Get end)

                // *** End programmer edit section *** (Клиент.Отчество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Отчество Set start)

                // *** End programmer edit section *** (Клиент.Отчество Set start)
                this.fОтчество = value;
                // *** Start programmer edit section *** (Клиент.Отчество Set end)

                // *** End programmer edit section *** (Клиент.Отчество Set end)
            }
        }
        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Фамилия CustomAttributes)

        // *** End programmer edit section *** (Клиент.Фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Фамилия Get start)

                // *** End programmer edit section *** (Клиент.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (Клиент.Фамилия Get end)

                // *** End programmer edit section *** (Клиент.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Фамилия Set start)

                // *** End programmer edit section *** (Клиент.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (Клиент.Фамилия Set end)

                // *** End programmer edit section *** (Клиент.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// Клиент.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.ЗаключениеДоговора CustomAttributes)

        // *** End programmer edit section *** (Клиент.ЗаключениеДоговора CustomAttributes)
        public virtual IIS.Kursovaya5.DetailArrayOfЗаключениеДоговора ЗаключениеДоговора
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.ЗаключениеДоговора Get start)

                // *** End programmer edit section *** (Клиент.ЗаключениеДоговора Get start)
                if ((this.fЗаключениеДоговора == null))
                {
                    this.fЗаключениеДоговора = new IIS.Kursovaya5.DetailArrayOfЗаключениеДоговора(this);
                }
                IIS.Kursovaya5.DetailArrayOfЗаключениеДоговора result = this.fЗаключениеДоговора;
                // *** Start programmer edit section *** (Клиент.ЗаключениеДоговора Get end)

                // *** End programmer edit section *** (Клиент.ЗаключениеДоговора Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.ЗаключениеДоговора Set start)

                // *** End programmer edit section *** (Клиент.ЗаключениеДоговора Set start)
                this.fЗаключениеДоговора = value;
                // *** Start programmer edit section *** (Клиент.ЗаключениеДоговора Set end)

                // *** End programmer edit section *** (Клиент.ЗаключениеДоговора Set end)
            }
        }
        
        /// <summary>
        /// Клиент.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.ОказаниеКонсультаций CustomAttributes)

        // *** End programmer edit section *** (Клиент.ОказаниеКонсультаций CustomAttributes)
        public virtual IIS.Kursovaya5.DetailArrayOfОказаниеКонсультаций ОказаниеКонсультаций
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.ОказаниеКонсультаций Get start)

                // *** End programmer edit section *** (Клиент.ОказаниеКонсультаций Get start)
                if ((this.fОказаниеКонсультаций == null))
                {
                    this.fОказаниеКонсультаций = new IIS.Kursovaya5.DetailArrayOfОказаниеКонсультаций(this);
                }
                IIS.Kursovaya5.DetailArrayOfОказаниеКонсультаций result = this.fОказаниеКонсультаций;
                // *** Start programmer edit section *** (Клиент.ОказаниеКонсультаций Get end)

                // *** End programmer edit section *** (Клиент.ОказаниеКонсультаций Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.ОказаниеКонсультаций Set start)

                // *** End programmer edit section *** (Клиент.ОказаниеКонсультаций Set start)
                this.fОказаниеКонсультаций = value;
                // *** Start programmer edit section *** (Клиент.ОказаниеКонсультаций Set end)

                // *** End programmer edit section *** (Клиент.ОказаниеКонсультаций Set end)
            }
        }
        
        /// <summary>
        /// Клиент.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.РасторжениеДоговора CustomAttributes)

        // *** End programmer edit section *** (Клиент.РасторжениеДоговора CustomAttributes)
        public virtual IIS.Kursovaya5.DetailArrayOfРасторжениеДоговора РасторжениеДоговора
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.РасторжениеДоговора Get start)

                // *** End programmer edit section *** (Клиент.РасторжениеДоговора Get start)
                if ((this.fРасторжениеДоговора == null))
                {
                    this.fРасторжениеДоговора = new IIS.Kursovaya5.DetailArrayOfРасторжениеДоговора(this);
                }
                IIS.Kursovaya5.DetailArrayOfРасторжениеДоговора result = this.fРасторжениеДоговора;
                // *** Start programmer edit section *** (Клиент.РасторжениеДоговора Get end)

                // *** End programmer edit section *** (Клиент.РасторжениеДоговора Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.РасторжениеДоговора Set start)

                // *** End programmer edit section *** (Клиент.РасторжениеДоговора Set start)
                this.fРасторжениеДоговора = value;
                // *** Start programmer edit section *** (Клиент.РасторжениеДоговора Set end)

                // *** End programmer edit section *** (Клиент.РасторжениеДоговора Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлиентE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентE", typeof(IIS.Kursovaya5.Клиент));
                }
            }
            
            /// <summary>
            /// "КлиентL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентL", typeof(IIS.Kursovaya5.Клиент));
                }
            }
        }
    }
}
