//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya5
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Расторжение договора.
    /// </summary>
    // *** Start programmer edit section *** (РасторжениеДоговора CustomAttributes)

    // *** End programmer edit section *** (РасторжениеДоговора CustomAttributes)
    [AutoAltered()]
    [Caption("Расторжение договора")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РасторжениеДоговораE", new string[] {
            "Дата as \'Дата\'",
            "Номер as \'Номер\'"})]
    public class РасторжениеДоговора : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private int fНомер;
        
        private IIS.Kursovaya5.ДиректорОтделаПоРаботеСКлиентами fДиректорОтделаПоРаботеСКлиентами;
        
        private IIS.Kursovaya5.Клиент fКлиент;
        
        // *** Start programmer edit section *** (РасторжениеДоговора CustomMembers)

        // *** End programmer edit section *** (РасторжениеДоговора CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (РасторжениеДоговора.Дата CustomAttributes)

        // *** End programmer edit section *** (РасторжениеДоговора.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (РасторжениеДоговора.Дата Get start)

                // *** End programmer edit section *** (РасторжениеДоговора.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (РасторжениеДоговора.Дата Get end)

                // *** End programmer edit section *** (РасторжениеДоговора.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасторжениеДоговора.Дата Set start)

                // *** End programmer edit section *** (РасторжениеДоговора.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (РасторжениеДоговора.Дата Set end)

                // *** End programmer edit section *** (РасторжениеДоговора.Дата Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (РасторжениеДоговора.Номер CustomAttributes)

        // *** End programmer edit section *** (РасторжениеДоговора.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (РасторжениеДоговора.Номер Get start)

                // *** End programmer edit section *** (РасторжениеДоговора.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (РасторжениеДоговора.Номер Get end)

                // *** End programmer edit section *** (РасторжениеДоговора.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасторжениеДоговора.Номер Set start)

                // *** End programmer edit section *** (РасторжениеДоговора.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (РасторжениеДоговора.Номер Set end)

                // *** End programmer edit section *** (РасторжениеДоговора.Номер Set end)
            }
        }
        
        /// <summary>
        /// Расторжение договора.
        /// </summary>
        // *** Start programmer edit section *** (РасторжениеДоговора.ДиректорОтделаПоРаботеСКлиентами CustomAttributes)

        // *** End programmer edit section *** (РасторжениеДоговора.ДиректорОтделаПоРаботеСКлиентами CustomAttributes)
        [PropertyStorage(new string[] {
                "ДиректорОтделаПоРаботеСКлиентами"})]
        [NotNull()]
        public virtual IIS.Kursovaya5.ДиректорОтделаПоРаботеСКлиентами ДиректорОтделаПоРаботеСКлиентами
        {
            get
            {
                // *** Start programmer edit section *** (РасторжениеДоговора.ДиректорОтделаПоРаботеСКлиентами Get start)

                // *** End programmer edit section *** (РасторжениеДоговора.ДиректорОтделаПоРаботеСКлиентами Get start)
                IIS.Kursovaya5.ДиректорОтделаПоРаботеСКлиентами result = this.fДиректорОтделаПоРаботеСКлиентами;
                // *** Start programmer edit section *** (РасторжениеДоговора.ДиректорОтделаПоРаботеСКлиентами Get end)

                // *** End programmer edit section *** (РасторжениеДоговора.ДиректорОтделаПоРаботеСКлиентами Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасторжениеДоговора.ДиректорОтделаПоРаботеСКлиентами Set start)

                // *** End programmer edit section *** (РасторжениеДоговора.ДиректорОтделаПоРаботеСКлиентами Set start)
                this.fДиректорОтделаПоРаботеСКлиентами = value;
                // *** Start programmer edit section *** (РасторжениеДоговора.ДиректорОтделаПоРаботеСКлиентами Set end)

                // *** End programmer edit section *** (РасторжениеДоговора.ДиректорОтделаПоРаботеСКлиентами Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Kursovaya5.Клиент.
        /// </summary>
        // *** Start programmer edit section *** (РасторжениеДоговора.Клиент CustomAttributes)

        // *** End programmer edit section *** (РасторжениеДоговора.Клиент CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Клиент"})]
        public virtual IIS.Kursovaya5.Клиент Клиент
        {
            get
            {
                // *** Start programmer edit section *** (РасторжениеДоговора.Клиент Get start)

                // *** End programmer edit section *** (РасторжениеДоговора.Клиент Get start)
                IIS.Kursovaya5.Клиент result = this.fКлиент;
                // *** Start programmer edit section *** (РасторжениеДоговора.Клиент Get end)

                // *** End programmer edit section *** (РасторжениеДоговора.Клиент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасторжениеДоговора.Клиент Set start)

                // *** End programmer edit section *** (РасторжениеДоговора.Клиент Set start)
                this.fКлиент = value;
                // *** Start programmer edit section *** (РасторжениеДоговора.Клиент Set end)

                // *** End programmer edit section *** (РасторжениеДоговора.Клиент Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РасторжениеДоговораE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасторжениеДоговораE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасторжениеДоговораE", typeof(IIS.Kursovaya5.РасторжениеДоговора));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of РасторжениеДоговора.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfРасторжениеДоговора CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfРасторжениеДоговора CustomAttributes)
    public class DetailArrayOfРасторжениеДоговора : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Kursovaya5.DetailArrayOfРасторжениеДоговора members)

        // *** End programmer edit section *** (IIS.Kursovaya5.DetailArrayOfРасторжениеДоговора members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type РасторжениеДоговора by index.
        /// </summary>
        /// <summary>
        /// Adds object with type РасторжениеДоговора.
        /// </summary>
        public DetailArrayOfРасторжениеДоговора(IIS.Kursovaya5.Клиент fКлиент) : 
                base(typeof(РасторжениеДоговора), ((ICSSoft.STORMNET.DataObject)(fКлиент)))
        {
        }
        
        public IIS.Kursovaya5.РасторжениеДоговора this[int index]
        {
            get
            {
                return ((IIS.Kursovaya5.РасторжениеДоговора)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Kursovaya5.РасторжениеДоговора dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
